Basic Forum Stats
========================================================

```{r echo=FALSE, results='hide'}
courseIDs<-c("aiplan","astro","crit","edc","equine","intro")
echo.sql<-TRUE # echo SQL statements
echo.flag<-TRUE #echo R source
fig.width.default<-5
fig.height.default<-5
options(knitr.table.format = 'markdown')
read_chunk("./Basic Mining Stats.R")
```

```{r INIT, echo=FALSE, message=FALSE}
#initialises the DB and sources helper.
```

Qty of forums, threads, posts, comments
-----------

```{r FORUM_COUNT, echo=FALSE}
```
### Forums

```{r echo=FALSE, results='asis'}
#curious align due to bug in knitr
kable(forumCount.df, row.names=T, align=rep("c", length(colnames(forumCount.df))))
```

### Threads

```{r echo=FALSE, results='asis'}
kable(threadCount.df, row.names=T, align=rep("c", length(colnames(threadCount.df))))
```

This does not count threads in a deleted parent forum as being deleted threads.

### Posts

```{r echo=FALSE, results='asis'}
kable(postCount.df, row.names=T, align=rep("c", length(colnames(postCount.df))))
```

This does not count posts in a deleted parent thread as being deleted posts.

### Comments

```{r echo=FALSE, results='asis'}
kable(commentCount.df, row.names=T, align=rep("c", length(colnames(commentCount.df))))
```

Look at mean of posts etc. Doesn\t work.

```{r POST_ANALYSIS, echo=FALSE}
```
```{r echo=FALSE, results='asis'}

for(i in 1:length(forum_posts)){
  print(i)
}

```

```{r TOPIC_MODELS, echo=FALSE}
```



```{r EXIT, echo=FALSE, message=FALSE}
#saves extracted data to an RData file and closes DB connection
```
```{r echo=FALSE}
## ****************************************************
## Created: Adam Cooper, Cetis, Oct 2013
## This source code was produced for The University of
## Edinburgh DEI as part of their MOOC initiative.
## ****************************************************

## ***Made available using the The MIT License (MIT)***
#The MIT License (MIT)
#Copyright (c) 2013 Adam Cooper, University of Bolton
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of
#this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#    
#    The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
## ************ end licence ***************
```